spring.datasource.url=
spring.datasource.driver-class-name=
spring.datasource.username=
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=

spring.jpa.database-platform=
spring.jpa.hibernate.ddl-auto=

jwt.secret=SECRET_KEY
jwt.expiration=3600000

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
app.cors.allowed-headers=*
app.cors.allow-credentials=true
